### ISSUE TITLE
Multiple partitions cannot Arm or Disarm

### ISSUE THREAD

**Issue by LavaGlass** [kk7ds/pynx584#34] opened 2019-07-18 05:33 UTC
READ UPDATE
Hi all,

I have a question and an issue. I connected up everything and got the software running then proceeded to try and arm my system. I have two partitions in my system one for the house and another for the shed. 

Lets just say the the alarm system got very angry when I typed in the arm command. The keypad in the shed was unresponsive to disarming and the whole time both screamers were going off. grrr.

My question is how does pynx584 handle multiple partitions? Is there another command I am missing?

Thanks.

**Comment by LavaGlass** [comment] 2019-07-18 07:01
Update.

I found the commands in the wiki for multiple partitions and running a summary spits out that both partitions are detected by pynx584. 

My new problem is that I cannot arm or disarm either partition whether it be arm from keypad, disarm with pynx584 or arm and disarm with pynx584 either does not work. (arming and disarming with keypads work perfectly normally) 

Any help is appreciated!

**Comment by kk7ds** [comment] 2019-07-18 13:50
I probably can't help you a whole lot as I don't have multiple partitions. However, I can say I'm sure that you having multiples isn't the reason for not being able to arm or disarm from the software. You need to enable all the admin commands to be allowed via the serial port, and arm needs to be an allowed operation without the code in order for pynx584 to do its thing.

**Comment by LavaGlass** [comment] 2019-07-19 00:39
@kk7ds Ok do you mean all the Primary Keypad stuff and other without code settings in the programming through the keypad?

**Comment by LavaGlass** [comment] 2019-07-19 00:48
Update.

I have now got arming partition 1 working. I think I had a bad connection to the TX pin on the serial to USB adaptor.

Partition 1 can Arm and Disarm now but partition 2 still does not respond to commands.

Oddly when pynx584 first starts a summary command only lists partition 1. I have to then arm or disarm partition 2 to make it show up.

**Comment by mobster1940** [comment] 2020-07-18 07:59
I have exactly the same problem, have you found any solution? Even if I send an arm/disarm command for the 2nd partition, it only arms/disarms the first one. I have connected Home Assistant and I get only 1 control panel for the alarm, which only effects the first partition. I would like to know if I can get a second alarm panel for the 2nd partition.

**Comment by mobster1940** [comment] 2020-08-10 08:39
Hello @kk7ds, I have created a pull request for arming/disarming partitions #44 . I had never written python before but I think it is a minor edit and I have been testing it for almost a month and it works perfectly. See for yourself and merge it if you like. I will try and edit the Home Assistant component too and open a pull request there.

**Comment by zipperten** [comment] 2020-09-09 15:30
Nice, i love to use this function, I have only used my alarm system for light automation before. 
Where do i allow Arming without code, i think it is missing on the wiki panel setup guide. "Segment 4,  Postition 6"

**Comment by nflo21** [comment] 2020-10-03 11:14
Hello,
I have a caddx alarm system (NX-8) with a NX-584 connected on it and a RPi3 with home assistant communicating with the NX-584 with an RS232-to-USB adapter.
My caddx system has 3 partitions.

The issue I have is that I can arm/disarm partition 1 and partition 2, but I cannot arm partition 3.
When I send command "nx584_client --partition 1 arm-exit" or "nx584_client --partition 3 arm-stay" it arms partition 1 for away mode and stay mode respectively. The same happens with partition 2.
The problem is when I send command "nx584_client --partition 3 arm-exit" to arm partition 3 the caddx system arms both partitions 1 and 2 and NOT partition 3  !!!!

Does some one has the same issue/problem?
@kk7ds do you have any suggestion on this issue?
Thanks in advance for your responses.

**Comment by nflo21** [comment] 2020-10-04 09:34
Today I figured out why with the command "nx584_client --partition 3 arm-exit" I cannot arm partition 3 but instead partitions 1 and 2 are armed.
The problem is that the number 3 passed in the above command is an integer and in binary mode is equal to "00000011". So NX-8 when receives the above number arms partition 1 and 2.
In order to arm only partition 3 you have to send the command "nx584_client --partition 4 arm-exit". In binary mode the decimal 4 is represented as: "00000100", the 3rd bit is on which corresponds to partition no.3.

**Comment by kk7ds** [comment] 2022-09-17 22:59
Can I close this or is there something that needs changing here?

**Comment by nflo21** [comment] 2022-09-18 08:09
Yes issue is resolve and you can close the thread.
Thank you.

**Closed as completed** 2022-09-18 14:06 UTC
